---

- hosts: all
  become: yes
  tasks:

    - name: install httpd package and update cache
      tags: RHEL,httpd
      package:
        name: 
          - "{{ http_package }}" 
          - "{{ php_package }}"
        state: latest 
        update_cache: yes

    - name: copy default html file for site
      tags: httpd, RHEL
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        mode: 0644
