---

- hosts: all
  become: yes
  tasks:

    - name: install httpd package and update cache
      package:
        name: 
          - "{{ http_package }}" 
          - "{{ php_package }}"
        state: latest 
        update_cache: yes
