- name: install httpd package and update cache
  tags: RHEL,httpd
  package:
    name:
      - "{{ apache_package_name }}" 
      - "{{ php_package_name }}" 
    state: latest
    update_cache: yes

- name: start httpd (RHEL)
  tags: httpd,RHEL
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"

- name: change e-mail address for admin
  tags: httpd,RHEL
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin adminansible@awashbank.com
  when: ansible_distribution == "RedHat"
  notify: restart_apache

- name: copy default html file for site
  tags: httpd, RHEL, html
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    mode: 0644

